const responseCodes = {
  CREATE_RECORD_SUCCESS: "CREATE_RECORD_SUCCESS",
  UPDATE_RECORD_SUCCESS: "UPDATE_RECORD_SUCCESS",
  DELETE_RECORD_SUCCESS: "DELETE_RECORD_SUCCESS",
  CREATE_RECORD_FAILED: "CREATE_RECORD_FAILED",
  UPDATE_RECORD_FAILED: "UPDATE_RECORD_FAILED",
  DELETE_RECORD_FAILED: "DELETE_RECORD_FAILED",
  RETRIEVE_RECORD: "RETRIEVE_RECORD",
  RETRIEVE_RECORD_LIST: "RETRIEVE_RECORD_LIST",
  EMPTY_RECORD_LIST: "EMPTY_RECORD_LIST",
  VALIDATION_CREATE_FAILED: "VALIDATION_CREATE_FAILED",
  VALIDATION_BASIC_INFO: "VALIDATION_BASIC_INFO",
  VALIDATION_BUSINESS_ACTIVITY: "VALIDATION_BUSINESS_ACTIVITY",
  VALIDATION_BFP_FORM: "VALIDATION_BFP_FORM",
  VALIDATION_OTHER_INFO: "VALIDATION_OTHER_INFO",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  ERROR_PROCESSING: "ERROR_PROCESSING",
  DATA_PROCESSING_ERROR: "DATA_PROCESSING_ERROR",
  LOGIN_FIRST: "LOGIN_FIRST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILED: "LOGOUT_FAILED",
  URL_EXPIRE: "LOGIN_FAILED",
  NOTIF_SUCCESS: "NOTIF_SUCCESS",
  NOTIF_FAILED: "NOTIF_FAILED",
};

const responseMessage = {
  ACCOUNT_NOT_ACTIVE: "The account is not yet activate!!",
  EMAIL_NOT_FOUND: "The provided email address is not found!!",
  EMAIL_ALREADY_TAKEN:
    "The email address or phone number provided is already in use.",
  INVALID_EMAIL: "The provided email address is incorrect!!",
  INVALID_PASSWORD: "The provided password is incorrect!!",
  LOGIN_FIRST: "Cannot access this page! Please sign in first.",
  URL_EXPIRE_MESSAGE: "This link was already expired.",
};

module.exports = { responseCodes, responseMessage };
