const responseCodes = {
  CREATE_RECORD_SUCCESS: "CREATE_RECORD_SUCCESS",
  UPDATE_RECORD_SUCCESS: "UPDATE_RECORD_SUCCESS",
  DELETE_RECORD_SUCCESS: "DELETE_RECORD_SUCCESS",
  CREATE_RECORD_FAILED: "CREATE_RECORD_FAILED",
  UPDATE_RECORD_FAILED: "UPDATE_RECORD_FAILED",
  DELETE_RECORD_FAILED: "DELETE_RECORD_FAILED",
  RETRIEVE_RECORD: "RETRIEVE_RECORD",
  RETRIEVE_RECORD_LIST: "RETRIEVE_RECORD_LIST",
  EMPTY_RECORD_LIST: "EMPTY_RECORD_LIST",
  VALIDATION_CREATE_FAILED: "VALIDATION_CREATE_FAILED",
  VALIDATION_UPDATE_FAILED: "VALIDATION_UPDATE_FAILED",
  CONTENT_NOT_FOUND: "CONTENT_NOT_FOUND",
  ERROR_PROCESSING: "ERROR_PROCESSING",
  DATA_PROCESSING_ERROR: "DATA_PROCESSING_ERROR",
  LOGIN_FIRST: "LOGIN_FIRST",
};

const responseMessage = {
  EMAIL_ALREADY_TAKEN:
    "The email address or phone number provided is already in use.",
};

module.exports = { responseCodes, responseMessage };
